export const CourseSeed = [
	{
		id: 1,
		title: 'Advanced topics in software engineering',
		description: '',
		summary: '소프트웨어 엔지니어링 강의입니다.',
		instructorId: 1,
		category1Id: 1,
		category2Id: 10,
		thumbnail:
			'https://mrdang-lectures.s3.ap-northeast-2.amazonaws.com/thumbnail-images/advanced-topics-in-software-engineering.jpg',
		difficulty: 1,
		createdAt: '2022-09-01T00:00:00.000Z',
	},
	{
		id: 2,
		title: 'Computer programming for engineers',
		description: '',
		summary: '공학 컴퓨터 프로그래밍',
		instructorId: 1,
		category1Id: 1,
		category2Id: 6,
		thumbnail:
			'https://mrdang-lectures.s3.ap-northeast-2.amazonaws.com/thumbnail-images/computer-programming-for-engineers.jpg',
		difficulty: 2,
		createdAt: '2022-09-01T00:00:00.000Z',
	},
	{
		id: 3,
		title: 'Data visualization',
		description: '',
		summary: '데이터 시각화',
		instructorId: 1,
		category1Id: 3,
		category2Id: 19,
		thumbnail:
			'https://mrdang-lectures.s3.ap-northeast-2.amazonaws.com/thumbnail-images/data-visualization.jpg',
		difficulty: 3,
		createdAt: '2022-09-01T00:00:00.000Z',
	},
	{
		id: 4,
		title: 'Machine learning with graphs',
		description: '',
		summary: '머신 러닝',
		instructorId: 1,
		category1Id: 3,
		category2Id: 18,
		thumbnail:
			'https://mrdang-lectures.s3.ap-northeast-2.amazonaws.com/thumbnail-images/machine-learning-with-graphs.jpg',
		difficulty: 1,
		createdAt: '2022-09-01T00:00:00.000Z',
	},
	{
		id: 5,
		title: '파이썬 프로그래밍',
		description: '',
		summary: '파이썬 프로그래밍 강의',
		instructorId: 1,
		category1Id: 1,
		category2Id: 6,
		thumbnail:
			'https://mrdang-lectures.s3.ap-northeast-2.amazonaws.com/thumbnail-images/python-programming.jpg',
		difficulty: 2,
		createdAt: '2022-09-01T00:00:00.000Z',
	},
	{
		id: 6,
		title: '성대의 성대한 특강',
		description: '',
		summary: '성균관대 특강',
		instructorId: 1,
		category1Id: 8,
		category2Id: 44,
		thumbnail:
			'https://mrdang-lectures.s3.ap-northeast-2.amazonaws.com/thumbnail-images/skku-special-lectures.png',
		difficulty: 3,
		createdAt: '2022-09-01T00:00:00.000Z',
	},
];
