export const CourseSeed = [
	{
		id: 1,
		title: '[테스트] 스프링 핵심 원리 - 고급편',
		description:
			'중급자를 위해 준비한 [백엔드, 웹 개발] 강의입니다. 스프링의 핵심 원리와 고급 기술들을 깊이있게 학습하고, 스프링을 자신있게 사용할 수 있습니다.',
		summary: '스프링 강의입니다.',
		instructorId: 1,
		category1Id: 1,
		category2Id: 3,
		thumbnail: 'ai.jpg',
		difficulty: 1,
		createdAt: '2022-01-31T15:00:00.000Z',
	},
	{
		id: 2,
		title: '[테스트] 처음 배우는 리액트 네이티브',
		description:
			'자바스크립트를 이용해서 모바일 앱을 만들 수 있는, 리액트 네이티브 입문자를 위한 강의입 니다. 리액트 네이티브를 개발할때 필요한 기초 지식을 익히고, 간단한 프로젝트를 진행합니다.',
		summary: '리액트 강의입니다.',
		instructorId: 1,
		category1Id: 1,
		category2Id: 5,
		thumbnail: 'ai.jpg',
		difficulty: 2,
		createdAt: '2022-01-31T15:00:00.000Z',
	},
	{
		id: 3,
		title: '[테스트] Flutter 인스타그램 클론 2.0',
		description:
			'이 강좌는 Firebase와 Flutter를 사용해서 간단한 서비스 앱을 어떻게 만들 수 있는지 방향성을 제시하는데 목적을 가지고 있습니다.',
		summary: '플러터 강의입니다.',
		instructorId: 1,
		category1Id: 1,
		category2Id: 5,
		thumbnail: 'ai.jpg',
		difficulty: 3,
		createdAt: '2022-01-31T15:00:00.000Z',
	},
	{
		id: 4,
		title: '[테스트] Vue.js 시작하기 - Age of Vue.js',
		description:
			'Vue.js로 쉽게 웹 개발할 수 있도록 기본 개념과 핵심 기능에 대해서 학습하고 구현해봅니다. 강좌를 들으시고 나면 Vue.js로 프런트엔드 개발을 하시는게 재밌어질거에요.',
		summary: '뷰 강의입니다.',
		instructorId: 1,
		category1Id: 1,
		category2Id: 2,
		thumbnail: 'ai.jpg',
		difficulty: 1,
		createdAt: '2022-01-31T15:00:00.000Z',
	},
	{
		id: 5,
		title: '[테스트] 코로나맵 개발자와 함께하는 지도서비스 만들기',
		description: '코로나맵 개발자가 알려주는 지도서비스 만들기 강의입니다.',
		summary: '지도서비스 강의입니다.',
		instructorId: 1,
		category1Id: 1,
		category2Id: 4,
		thumbnail: 'ai.jpg',
		difficulty: 2,
		createdAt: '2022-01-31T15:00:00.000Z',
	},
	{
		id: 6,
		title: '[테스트] AWS 클라우드 서비스 인프라 구축 이해와 해킹, 보안',
		description:
			'IT 서비스가 클라우드 환경으로 빠르게 전환되고 있습니다. 아마존 AWS 클라우드 환경 보안을 위해 알아야 할 기본적인 가상 인프라 구축부터, 각 영역별 보안 위협 모니터링, 취약점 진단 관점을 통해보안 실무를 배우게 됩니다.',
		summary: 'AWS 강의입니다.',
		instructorId: 1,
		category1Id: 2,
		category2Id: 12,
		thumbnail: 'ai.jpg',
		difficulty: 3,
		createdAt: '2022-01-31T15:00:00.000Z',
	},
	{
		id: 7,
		title: '[테스트] 리눅스 커널 해킹. A부터 Z까지',
		description:
			'리눅스 커널의 각종 보호 기법과 그에 대한 우회 방안, 다양한 취약점들을 분석해보는 강의이며 강의별로 실습 예제가 제공 됩니다.',
		summary: '리눅스 강의입니다.',
		instructorId: 1,
		category1Id: 2,
		category2Id: 12,
		thumbnail: 'ai.jpg',
		difficulty: 1,
		createdAt: '2022-01-31T15:00:00.000Z',
	},
	{
		id: 8,
		title: '[테스트] 블록체인 기반의 스마트컨트랙트 개발',
		description:
			'이더리움 기반의 DAPP 개발로 블록체인을 배워보세요. Smart Contract의 구현을 통해서 실전 개발에 대한 지식도 알 수 있습니다.',
		summary: '블록체인 강의입니다.',
		instructorId: 1,
		category1Id: 2,
		category2Id: 15,
		thumbnail: 'ai.jpg',
		difficulty: 2,
		createdAt: '2022-01-31T15:00:00.000Z',
	},
	{
		id: 9,
		title: '[테스트] 초보를 위한 도커 안내서',
		description:
			'도커를 1도 모르는 입문자, 초보자분들을 위한 도커 안내서 입니다. 복잡한 내용을 제외하고 도커가 왜 인기가 많고 어떻게 사용하는지 빠르게 익힐 수 있도록 집중하였습니다.',
		summary: '도커 강의입니다.',
		instructorId: 1,
		category1Id: 2,
		category2Id: 14,
		thumbnail: 'ai.jpg',
		difficulty: 3,
		createdAt: '2022-01-31T15:00:00.000Z',
	},
	{
		id: 10,
		title: '[테스트] 패킷트레이서를 활용한 컴퓨터네트워크',
		description:
			'컴퓨터 네트워크의 이론을 학습합니다. 시뮬레이션 프로그램을 사용하여 네트워크를 직접 구 성해봄으로써 네트워크에 대해서 확실하게 공부해보세요. 설명이 잘 되어 있는 강의 자료를 제공합니다.',
		summary: '네트워크 강의입니다.',
		instructorId: 1,
		category1Id: 2,
		category2Id: 13,
		thumbnail: 'ai.jpg',
		difficulty: 1,
		createdAt: '2022-01-31T15:00:00.000Z',
	},
	{
		id: 11,
		title: '[테스트] 증권 데이터 수집과 분석으로 신호와 소음 찾기',
		description:
			'투자 강의가 아닙니다. 증권 데이터를 통한 데이터 수집, 분석과 시각화를 다룹니다. 다양한 데이터 포맷을 다루며 다양한 텍스트 전처리 기법을 익힙니다. 시계열 데이터의 시각화 기법과 스케일에 대한 표현 방법 주가 데이터를 해석하기 위한 몇 가지 기법을 다룹니다. 이 강의는 데이터 분석을 통해 인사이트 를 얻는 방법을 알아가는 강좌입니다. 주가 데이터를 통해 배운 내용을 시계열이 활용되는 수요량, 재고량,판매량, 트래픽량 등의 데이터를 수집, 분석, 시각화에 활용해 볼 수 있도록 구성 되어있습니다.',
		summary: '증권 강의입니다.',
		instructorId: 1,
		category1Id: 3,
		category2Id: 17,
		thumbnail: 'ai.jpg',
		difficulty: 2,
		createdAt: '2022-01-31T15:00:00.000Z',
	},
	{
		id: 12,
		title: '[테스트] 딥러닝 CNN 완벽 가이드 - Fundamental 편',
		description:
			'딥러닝·CNN 핵심 이론부터 다양한 CNN 모델 구현 방법, 실전 문제를 통한 실무 딥러닝 개발노하우까지, 딥러닝 CNN 기술 전문가로 거듭나고 싶다면 이 강의와 함께하세요 :)',
		summary: '딥러닝 강의입니다.',
		instructorId: 1,
		category1Id: 3,
		category2Id: 18,
		thumbnail: 'ai.jpg',
		difficulty: 3,
		createdAt: '2022-01-31T15:00:00.000Z',
	},
	{
		id: 13,
		title: '[테스트] 실전 인공지능으로 이어지는 딥러닝 개념 잡기',
		description:
			'다양한 인공 신경망의 구조와 동작 원리를 이해하고 좋은 모델을 만드는데 필요한 필수 지식 을 전달하는 강의입니다.',
		summary: '딥러닝 강의입니다.',
		instructorId: 1,
		category1Id: 3,
		category2Id: 18,
		thumbnail: 'ai.jpg',
		difficulty: 1,
		createdAt: '2022-01-31T15:00:00.000Z',
	},
	{
		id: 14,
		title: '[테스트] Node.js로 웹 크롤링하기',
		description:
			'네이버, 아마존, 트위터, 유튜브, 페이스북, 인스타그램, unsplash.com 등의 사이트를 크롤링하며 실전에 적용해봅니다.',
		summary: '노드 강의입니다.',
		instructorId: 1,
		category1Id: 3,
		category2Id: 20,
		thumbnail: 'ai.jpg',
		difficulty: 2,
		createdAt: '2022-01-31T15:00:00.000Z',
	},
	{
		id: 15,
		title: '[테스트] [R을 R려줘] R 데이터 시각화',
		description:
			'R 기반 데이터 시각화를 가장 쉽게 설명한 강의. (거의) 다 알려드림. 마지막에는 COVID-19 �백백신 접종 데이터를 지도에 뿌려봅니다!',
		summary: 'R 강의입니다.',
		instructorId: 1,
		category1Id: 3,
		category2Id: 19,
		thumbnail: 'ai.jpg',
		difficulty: 3,
		createdAt: '2022-01-31T15:00:00.000Z',
	},
	{
		id: 16,
		title: '[테스트] 3dsmax 초급부터 전문가까지 - 한방에 끝내는 3dsmax 강좌',
		description:
			'3DS MAX 의 모든것을 다루는 강좌. 입문자도 누구나 따라오기만 하면 전문가 수준으로 인도해주는 원샷 원킬 3DS max 강좌 입니다. 기본 개념부터 고급기술 노하우까지 재미있는 예제를 통해 하나하나 알려주는 친절하고도 방대한 강의 3DS MAX 는 이거 하나로 끝내보세요',
		summary: '3dsmax 강의입니다.',
		instructorId: 1,
		category1Id: 4,
		category2Id: 22,
		thumbnail: 'ai.jpg',
		difficulty: 1,
		createdAt: '2022-01-31T15:00:00.000Z',
	},
	{
		id: 17,
		title: '[테스트] UX/UI 시작하기 : UI 디자인',
		description:
			'신입 UI/UX 디자이너가 되고자 하거나, UI 디자인에 대해 알아보고 싶은 분들을 대상으로 한 UI 디자인 기초 강의입니다. UI 디자인에 대한 기본적인 지식 및 실무에서 꼭 알아야 할 디자인 팁 등을 배울 수 있습니다.',
		summary: '디자인 강의입니다.',
		instructorId: 1,
		category1Id: 4,
		category2Id: 24,
		thumbnail: 'ai.jpg',
		difficulty: 2,
		createdAt: '2022-01-31T15:00:00.000Z',
	},
	{
		id: 18,
		title: '[테스트] 애니메이션과 이모티콘 만드는 진짜 애니메이트 클래스',
		description:
			'나만의 애니메이션과 움직이는 이모티콘을 만들고 싶어하는 초보분들을 위한 어도비 애니메이트 수업입니다.',
		summary: '애니메이션 강의입니다.',
		instructorId: 1,
		category1Id: 4,
		category2Id: 25,
		thumbnail: 'ai.jpg',
		difficulty: 3,
		createdAt: '2022-01-31T15:00:00.000Z',
	},
	{
		id: 19,
		title: '[테스트] 피그마로 콘텐츠 디자인하기',
		description:
			'피그마는 UX/UI전용 툴이다? 아닙니다. 여러분의 썸네일, 광고소재, 상세페이지까지 피그마하나로 만들어보겠습니다.',
		summary: '피그마 강의입니다.',
		instructorId: 1,
		category1Id: 4,
		category2Id: 25,
		thumbnail: 'ai.jpg',
		difficulty: 2,
		createdAt: '2022-01-31T15:00:00.000Z',
	},
	{
		id: 20,
		title: '[테스트] 유니티3D를 사용한 VR 제작 기초',
		description:
			'유니티를 사용하여 VR 환경을 구축하며 VR 컨텐츠를 개발하기 위해 필요한 기본적인 기능을구현해봅니다.',
		summary: '유니티 강의입니다.',
		instructorId: 1,
		category1Id: 4,
		category2Id: 28,
		thumbnail: 'ai.jpg',
		difficulty: 1,
		createdAt: '2022-01-31T15:00:00.000Z',
	},
	{
		id: 21,
		title: '[테스트] 진짜 현업에서 쓰이는 직장인의 실무 엑셀 - 데이터 가공부터 분석까지',
		description:
			"현재 엑셀의 가장 트렌디한 방법으로 데이터를 효율적, 과학적으로 가공, 분석함에 '표준'이 되는 과정입니다.",
		summary: '엑셀 강의입니다.',
		instructorId: 1,
		category1Id: 5,
		category2Id: 31,
		thumbnail: 'ai.jpg',
		difficulty: 3,
		createdAt: '2022-01-31T15:00:00.000Z',
	},
	{
		id: 22,
		title: '[테스트] [한글NEO] 한번에 끝내는 문서작성 & ITQ 한글 자격증 취득',
		description:
			'한글NEO 프로그램을 이용하여, 문서작성 기초부터 실무활용까지 그리고 자격증 취득까지 한번에! 기초가 부족하고 실무에서 문서작성을 원하는 분들이 이과정을 통해서 자격증도 취득하고, 문서작성을 할 수 있다고 자신있게 말씀드립니다.',
		summary: '한글 강의입니다.',
		instructorId: 1,
		category1Id: 5,
		category2Id: 31,
		thumbnail: 'ai.jpg',
		difficulty: 1,
		createdAt: '2022-01-31T15:00:00.000Z',
	},
	{
		id: 23,
		title: '[테스트] 비트윈 마케터가 7년 동안 실제로 해본 브랜드 마케팅 A to Z',
		description:
			'‘커플앱 비트윈’ 마케터가 7년 동안 실제 집행한 브랜드 마케팅 사례를 통해, 수박 겉핥기식 이 아닌 진짜 현장에서 하는 고민과 해결 방법, 인사이트를 배울 수 있습니다.',
		summary: '마케팅 강의입니다.',
		instructorId: 1,
		category1Id: 5,
		category2Id: 32,
		thumbnail: 'ai.jpg',
		difficulty: 2,
		createdAt: '2022-01-31T15:00:00.000Z',
	},
	{
		id: 24,
		title: '[테스트] 3시간에 끝내는 디지털 마케팅의 모든 것',
		description:
			'1) 디지털 마케팅의 거대한 흐름을 파악하여, 디지털 마케터가 되기위한 방법론들을 살펴봅니다. 2) 디지털 마케팅의 핵심 툴인 구글 애널리틱스를 맛보는 강의를 진행합니다.',
		summary: '마케팅 강의입니다.',
		instructorId: 1,
		category1Id: 5,
		category2Id: 32,
		thumbnail: 'ai.jpg',
		difficulty: 3,
		createdAt: '2022-01-31T15:00:00.000Z',
	},
	{
		id: 25,
		title: '[테스트] 비트코인 알고리즘 트레이딩 봇 개발',
		description: '프로그래밍으로 나만의 수익모델을 만들어 보세요.',
		summary: '비트코인 강의입니다.',
		instructorId: 1,
		category1Id: 5,
		category2Id: 35,
		thumbnail: 'ai.jpg',
		difficulty: 1,
		createdAt: '2022-01-31T15:00:00.000Z',
	},
	{
		id: 26,
		title: '[테스트] 게임 엔진을 지탱하는 게임 수학',
		description:
			'게임을 구성하는 가상 세계가 수학으로 어떻게 만들어지는지 기반에서부터 하나씩 다루는 강 의입니다. 기반 수학을 통해 게임 엔진의 구성 원리를 이해하고, 3차원 공간을 구성하는 실질적인 게임 수학 을 학습합니다.',
		summary: '수학 강의입니다.',
		instructorId: 1,
		category1Id: 6,
		category2Id: 37,
		thumbnail: 'ai.jpg',
		difficulty: 2,
		createdAt: '2022-01-31T15:00:00.000Z',
	},
	{
		id: 27,
		title: '[테스트] 선형대수학개론',
		description:
			'이 강좌에서는 선형대수학개론을 다루며, 강의를 통해 선형대수학개론을 마스터할 수 있습니 다.',
		summary: '수학 강의입니다.',
		instructorId: 1,
		category1Id: 6,
		category2Id: 37,
		thumbnail: 'ai.jpg',
		difficulty: 3,
		createdAt: '2022-01-31T15:00:00.000Z',
	},
	{
		id: 28,
		title: '[테스트] 벡터 미적분학 시리즈1 - 미분 기초',
		description:
			'이 강좌를 통해 수강생은 벡터 미적분학 (미적분2)에서 미분의 기초에 대해 다질 수 있습니다.',
		summary: '수학 강의입니다.',
		instructorId: 1,
		category1Id: 6,
		category2Id: 37,
		thumbnail: 'ai.jpg',
		difficulty: 1,
		createdAt: '2022-01-31T15:00:00.000Z',
	},
	{
		id: 29,
		title: '[테스트] 실무에서 바로 쓰는 영어 이메일',
		description:
			"비즈니스 영어, 특히 이메일 작성에서 어려움을 겪으시는 분들이 빠른 시간 안에 치트키 쓰듯이 바로 바로 효과를 볼 수 있는 '외국계 무역 기업 현업 8년차' 영어 이메일 전문가의 노하우가 담긴 강의입니다.",
		summary: '영어 강의입니다.',
		instructorId: 1,
		category1Id: 6,
		category2Id: 38,
		thumbnail: 'ai.jpg',
		difficulty: 2,
		createdAt: '2022-01-31T15:00:00.000Z',
	},
	{
		id: 30,
		title: '[테스트] 스피킹 강자로 만들어주는 만능 영어회화패턴 12가지',
		description:
			'전문영어강사의 현장 노하우가 담긴 체계적 & 통합적 패턴 강의로 영어실력을 끌어 올려보세 요. 영알못을 단기간에 영어 실력자로 만든 노하우, <영작-말하기-대화>의 Magical 3 Step을 경험해보세요.',
		summary: '영어 강의입니다.',
		instructorId: 1,
		category1Id: 6,
		category2Id: 38,
		thumbnail: 'ai.jpg',
		difficulty: 3,
		createdAt: '2022-01-31T15:00:00.000Z',
	},
	{
		id: 31,
		title: '[테스트] 오늘부터 개발자 - 개발자를 준비하기 전 꼭 알아야 할 것',
		description:
			'오늘부터 (나도) 개발자! 개발자에 도전하는 분들을 위해 기본적인 개발 지식부터 준비 방법, 각종 노하우까지 전해드립니다.',
		summary: '개발 강의입니다.',
		instructorId: 1,
		category1Id: 7,
		category2Id: 40,
		thumbnail: 'ai.jpg',
		difficulty: 1,
		createdAt: '2022-01-31T15:00:00.000Z',
	},
	{
		id: 32,
		title: '[테스트] 비전공자를 위한 넓고 얇은 IT 지식 & 나의 개발 유형 알아보기! <M.B.I.T>',
		description:
			'나의 개발 유형을 테스트해보자! MBTI아닌 MBIT! My Best IT personalities! 개발에 대한 전 반적인 내용을 살펴보고 나에게 가장 잘 맞는 개발 적성을 알아볼 수 있습니다.',
		summary: '개발 강의입니다.',
		instructorId: 1,
		category1Id: 7,
		category2Id: 40,
		thumbnail: 'ai.jpg',
		difficulty: 2,
		createdAt: '2022-01-31T15:00:00.000Z',
	},
	{
		id: 33,
		title: '[테스트] 퍼블리셔 취업 진짜 실전 가이드',
		description:
			'퍼블리셔 취업을 위한 진짜 가이드 전자책(PDF)으로 효율적인 퍼블리싱 학습방법, 좋은 퍼블 리싱 강의 잘 가르치는 퍼블리싱 강사 고르는 안목, 신입이지만 경력자처럼 퍼블리싱하는 요령, 바람직한 코 딩 습관과 원칙, 개인 포트폴리오 홈페이지 제작 방법, 디자이너 개발자와의 협업 요령, 퍼블리셔로 알아야할 필수 사이트, 포토샵 UI 디자인 실력키우기 등 퍼블리셔 취업을 위해 반드시 알아야 하는 HTML+CSS+JQUERY 퍼블리싱 기본기를 상세하게 알려드립니다. 또한, 국비지원 퍼블리셔 과정에 대해 상세히 설명합니다.',
		summary: '퍼블리셔 강의입니다.',
		instructorId: 1,
		category1Id: 7,
		category2Id: 40,
		thumbnail: 'ai.jpg',
		difficulty: 3,
		createdAt: '2022-01-31T15:00:00.000Z',
	},
	{
		id: 34,
		title: '[테스트] 스타트업 A to Z',
		description:
			'스타트업에 대한 솔직한 얘기, 사업자 등록부터 지분 관계, 채용, 대출 한도까지 그동안 스타트업에 관련해 상담해드렸던 내용을 강의로 만들어 보았습니다!',
		summary: '스타트업 강의입니다.',
		instructorId: 1,
		category1Id: 7,
		category2Id: 42,
		thumbnail: 'ai.jpg',
		difficulty: 1,
		createdAt: '2022-01-31T15:00:00.000Z',
	},
	{
		id: 35,
		title: '[테스트] 스타트업 아이템발굴부터 투자유치까지',
		description:
			'스타트업을 하고 싶지만 막연한 두려움과 방법을 몰라 고민하시는 분들께 구체적인 방법론을 제시합니다. 네이버, 카카오, 야후에서 근무했고 실제로 2번의 창업 경험이 있는 실무자가 알려주는 스타트업에 대한 모든 것! 아이템 선정부터 팀빌딩, 사업계획서 작성, 비즈니스모델 수립, 투자유치까지! 실제 현장에서 배운 생생한 노하우를 전달해드립니다. 준비된 창업만이 패가망신을 피할 수 있습니다.',
		summary: '스타트업 강의입니다.',
		instructorId: 1,
		category1Id: 7,
		category2Id: 42,
		thumbnail: 'ai.jpg',
		difficulty: 2,
		createdAt: '2022-01-31T15:00:00.000Z',
	},
	{
		id: 36,
		title: '[테스트] 직장인을 위한 자산관리 101',
		description:
			'직장인을 위한 현실적인 자산관리와 투자 방법론을 다루는 101 강의입니다. 스스로의 투자 성향에 맞춘 포트폴리오를 구성하고 응용하는 방법을 다룹니다.',
		summary: '자산관리 강의입니다.',
		instructorId: 1,
		category1Id: 8,
		category2Id: 44,
		thumbnail: 'ai.jpg',
		difficulty: 3,
		createdAt: '2022-01-31T15:00:00.000Z',
	},
	{
		id: 37,
		title: '[테스트] 보통 직장인의 위대한 글쓰기',
		description: '퇴근 후 나는 작가가 된다',
		summary: '글쓰기 강의입니다.',
		instructorId: 1,
		category1Id: 8,
		category2Id: 44,
		thumbnail: 'ai.jpg',
		difficulty: 1,
		createdAt: '2022-01-31T15:00:00.000Z',
	},
	{
		id: 38,
		title: '[테스트] [기초스피치] 12년차 아나운서에게 배우는 말 잘하는 방법!',
		description:
			'말을 잘하고 싶나요? 발표할 때 자꾸 긴장하나요? 12년차 아나운서 흥버튼에게 체계적으로 스피치를 배워 보세요. 당신의 인생이 달라질 겁니다.',
		summary: '말하기 강의입니다.',
		instructorId: 1,
		category1Id: 8,
		category2Id: 44,
		thumbnail: 'ai.jpg',
		difficulty: 2,
		createdAt: '2022-01-31T15:00:00.000Z',
	},
	{
		id: 39,
		title: '[테스트] 배우면 평생 써먹는 일과 삶의 핵무기 - 돈이 되는 글쓰기',
		description:
			'보고서, 마케팅, 유튜브, SNS! 당신이 어디서 무엇을 하든 글쓰기 능력이 성공을 좌우합니다. 독이 되는 글이 아닌, ‘돈’이 되는 글쓰기가 답! 대한민국 대표 글쓰기 코치가 전하는 <직장인을 위한 돈이 되는 글쓰기> 족집게 노하우에 주목해 보세요!',
		summary: '글쓰기 강의입니다.',
		instructorId: 1,
		category1Id: 8,
		category2Id: 44,
		thumbnail: 'ai.jpg',
		difficulty: 3,
		createdAt: '2022-01-31T15:00:00.000Z',
	},
	{
		id: 40,
		title: '[테스트] 리그 오브 레전드 프로게이머처럼 플레이하기:BASIC',
		description:
			'리그 오브 레전드를 플레이할 때 꼭 필요한 기본 개념과 상황에 맞는 플레이를 기초부터 차근차근 알려드립니다.',
		summary: '게임 강의입니다.',
		instructorId: 1,
		category1Id: 8,
		category2Id: 44,
		thumbnail: 'ai.jpg',
		difficulty: 1,
		createdAt: '2022-01-31T15:00:00.000Z',
	},
	{
		id: 41,
		title: '성대의 성대한 특강',
		description: '성균관대학교 SW 중심대학 교수님들의 특강입니다.',
		summary: 'CS 강의입니다',
		instructorId: 1,
		category1Id: 8,
		category2Id: 16,
		thumbnail: 'ai.jpg',
		difficulty: 1,
		createdAt: '2022-01-31T15:00:00.000Z',
	},
];
