export const Lecture_seed = [
    {
        id: 1,
        title: '[테스트] 개발 환경 설치',
        filename: '[테스트 파일명] 개발 환경 설치',
        course_id : 1,
        section_id: 1,
    },
    {
        id: 2,
        title: '[테스트] 스프링 부트 프로젝트 생성 ',
        filename: '[테스트 파일명] 스프링 부트 프로젝트 생성',
        course_id : 1,
        section_id: 1,
    },
    {
        id: 3,
        title: '[테스트] IntelliJ 자동빌드 환경 설정 ',
        filename: '[테스트 파일명] IntelliJ 자동빌드 환경 설정',
        course_id : 1,
        section_id: 2,
    },
    {
        id: 4,
        title: '[테스트] 고급 url 매핑',
        filename: '[테스트 파일명] 고급 url 매핑',
        course_id : 1,
        section_id: 2,
    },
    {
        id: 5,
        title: '[테스트] 홈, 등록, 로그인 화면 개발 ',
        filename: '[테스트 파일명] 홈, 등록, 로그인 화면 개발',
        course_id : 1,
        section_id: 2,
    },
    {
        id: 6,
        title: '[테스트] 웹사이트에 React 추가하기',
        filename: '[테스트 파일명] 웹사이트에 React 추가하기',
        course_id : 2,
        section_id: 1,
    },
    {
        id: 7,
        title: '[테스트] Components 와 Props',
        filename: '[테스트 파일명] Components 와 Props',
        course_id : 2,
        section_id: 2,
    },
    {
        id: 8,
        title: '[테스트] Component 만들고 추출하기',
        filename: '[테스트 파일명] Component 만들고 추출하기',
        course_id : 2,
        section_id: 2,
    },
    {
        id: 9,
        title: '[테스트] Event 다루기',
        filename: '[테스트 파일명] Event 다루기',
        course_id : 2,
        section_id: 3,
    },
    {
        id: 10,
        title: '[테스트] 로그안 버튼 렌더링하기',
        filename: '[테스트 파일명] 로그인 버튼 렌더링하기',
        course_id : 2,
        section_id: 3,
    },
    {
        id: 11,
        title: '[테스트] Flutter vs React Native',
        filename: '[테스트 파일명] Flutter vs React Native',
        course_id : 3,
        section_id: 1,
    },
    {
        id: 12,
        title: '[테스트] Flutter 개발을 위한 환경 구축하기 ',
        filename: '[테스트 파일명] Flutter 개발을 위한 환경 구축하기',
        course_id : 3,
        section_id: 1,
    },
    {
        id: 13,
        title: '[테스트] 영화 목록 데이터 연동 및 데이터 요청',
        filename: '[테스트 파일명] 영화 목록 데이터 연동 및 데이터 요청',
        course_id : 3,
        section_id: 1,
    },
    {
        id: 14,
        title: '[테스트] 정렬 순서에 따라 데이터 호출하기',
        filename: '[테스트 파일명] 정렬 순서에 따라 데이터 호출하기',
        course_id : 3,
        section_id: 1,
    },
    {
        id: 15,
        title: '[테스트] 데이터를 가져오는 동안 로딩 화면 보여주기',
        filename: '[테스트 파일명] 데이터를 가져오는 동안 로딩 화면 보여주기',
        course_id : 3,
        section_id: 1,
    },
    {
        id: 16,
        title: '[테스트] Vue 인스턴스 생성하기',
        filename: '[테스트 파일명] Vue 인스턴스 생성하기',
        course_id : 4,
        section_id: 1,
    },
    {
        id: 17,
        title: '[테스트] 여러 개의 뷰 인스턴스 사용하기',
        filename: '[테스트 파일명] 여러 개의 뷰 인스턴스 사용하기 ',
        course_id : 4,
        section_id: 2,
    },
    {
        id: 18,
        title: '[테스트] 부모&자식 컴포넌트로 데이터 보내기',
        filename: '[테스트 파일명] 부모&자식 컴포넌트로 데이터 보내기',
        course_id : 4,
        section_id: 3,
    },
    {
        id: 19,
        title: '[테스트] 뷰 인스턴스 라이프사이클 ',
        filename: '[테스트 파일명] 뷰 인스턴스 라이프사이클 ',
        course_id : 4,
        section_id: 4,
    },
    {
        id: 20,
        title: '[테스트] Vue Getters & Map 핼퍼',
        filename: '[테스트 파일명] Vue Getters & Map 햂퍼',
        course_id : 4,
        section_id: 4,
    },
    {
        id: 21,
        title: '[테스트] 도커 이미지 pull',
        filename: '[테스트 파일명] 도커 이미지 pull',
        course_id : 5,
        section_id: 1,
    },
    {
        id: 22,
        title: '[테스트] 도커 컨테이너 run',
        filename: '[테스트 파일명] 도커 컨테이너 run',
        course_id : 5,
        section_id: 2,
    },
    {
        id: 23,
        title: '[테스트] 도커 네트워크',
        filename: '[테스트 파일명] 도커 네트워크',
        course_id : 5,
        section_id: 3,
    },
    {
        id: 24,
        title: '[테스트] 도커 명령어 실행',
        filename: '[테스트 파일명] 도커 명령어 실행',
        course_id : 5,
        section_id: 4,
    },
    {
        id: 25,
        title: '[테스트] 호스트와 컨테이너의 파일 시스템 연결',
        filename: '[테스트 파일명] 호스트와 컨테이너 파일 시스템 연결',
        course_id : 5,
        section_id: 5,
    },
    {
        id: 26,
        title: '[테스트] 클라우드에 대한 이해',
        filename: '[테스트 파일명] 클라우드에 대한 이해',
        course_id : 6,
        section_id: 1,
    },
    {
        id: 27,
        title: '[테스트] 가상 서버 만들기 EC2',
        filename: '[테스트 파일명] 가상 서버 만들기 EC2',
        course_id : 6,
        section_id: 1,
    },
    {
        id: 28,
        title: '[테스트] ssh로 EC2 인스턴스 접속하기',
        filename: '[테스트 파일명] ssh로 EC2 인스턴스 접속하기',
        course_id : 6,
        section_id: 1,
    },
    {
        id: 29,
        title: '[테스트] 가상 서버의 용량 조절하기 EBS',
        filename: '[테스트 파일명] 가상 서버의 용량 조절하기 EBS',
        course_id : 6,
        section_id: 1,
    },
    {
        id: 30,
        title: '[테스트] 자동으로 크기 조절하기 Auto Scaling',
        filename: '[테스트 파일명] 자동으로 크기 조절하기 Auto Scaling',
        course_id : 6,
        section_id: 2,
    },
];