export const Lecture = [
	{
		id: 1,
		title: '[테스트] 개발 환경 설치',
		duration: 600,
		filename: '[테스트 파일명] 개발 환경 설치',
		courseId: 1,
		sectionId: 1,
		createdAt: new Date(2022, 1, 1),
	},
	{
		id: 2,
		title: '[테스트] 스프링 부트 프로젝트 생성 ',
		duration: 600,
		filename: '[테스트 파일명] 스프링 부트 프로젝트 생성',
		courseId: 1,
		sectionId: 1,
		createdAt: new Date(2022, 1, 1),
	},
	{
		id: 3,
		title: '[테스트] IntelliJ 자동빌드 환경 설정 ',
		duration: 600,
		filename: '[테스트 파일명] IntelliJ 자동빌드 환경 설정',
		courseId: 1,
		sectionId: 2,
		createdAt: new Date(2022, 1, 1),
	},
	{
		id: 4,
		title: '[테스트] 고급 url 매핑',
		duration: 600,
		filename: '[테스트 파일명] 고급 url 매핑',
		courseId: 1,
		sectionId: 2,
		createdAt: new Date(2022, 1, 1),
	},
	{
		id: 5,
		title: '[테스트] 홈, 등록, 로그인 화면 개발 ',
		duration: 600,
		filename: '[테스트 파일명] 홈, 등록, 로그인 화면 개발',
		courseId: 1,
		sectionId: 2,
		createdAt: new Date(2022, 1, 1),
	},
	{
		id: 6,
		title: '[테스트] 웹사이트에 React 추가하기',
		duration: 600,
		filename: '[테스트 파일명] 웹사이트에 React 추가하기',
		courseId: 2,
		sectionId: 3,
		createdAt: new Date(2022, 1, 1),
	},
	{
		id: 7,
		title: '[테스트] Components 와 Props',
		duration: 600,
		filename: '[테스트 파일명] Components 와 Props',
		courseId: 2,
		sectionId: 4,
		createdAt: new Date(2022, 1, 1),
	},
	{
		id: 8,
		title: '[테스트] Component 만들고 추출하기',
		duration: 600,
		filename: '[테스트 파일명] Component 만들고 추출하기',
		courseId: 2,
		sectionId: 4,
		createdAt: new Date(2022, 1, 1),
	},
	{
		id: 9,
		title: '[테스트] Event 다루기',
		duration: 600,
		filename: '[테스트 파일명] Event 다루기',
		courseId: 2,
		sectionId: 5,
		createdAt: new Date(2022, 1, 1),
	},
	{
		id: 10,
		title: '[테스트] 로그안 버튼 렌더링하기',
		duration: 600,
		filename: '[테스트 파일명] 로그인 버튼 렌더링하기',
		courseId: 2,
		sectionId: 5,
		createdAt: new Date(2022, 1, 1),
	},
	{
		id: 11,
		title: '[테스트] Flutter vs React Native',
		duration: 600,
		filename: '[테스트 파일명] Flutter vs React Native',
		courseId: 3,
		sectionId: 6,
		createdAt: new Date(2022, 1, 1),
	},
	{
		id: 12,
		title: '[테스트] Flutter 개발을 위한 환경 구축하기 ',
		duration: 600,
		filename: '[테스트 파일명] Flutter 개발을 위한 환경 구축하기',
		courseId: 3,
		sectionId: 6,
		createdAt: new Date(2022, 1, 1),
	},
	{
		id: 13,
		title: '[테스트] 영화 목록 데이터 연동 및 데이터 요청',
		duration: 600,
		filename: '[테스트 파일명] 영화 목록 데이터 연동 및 데이터 요청',
		courseId: 3,
		sectionId: 6,
		createdAt: new Date(2022, 1, 1),
	},
	{
		id: 14,
		title: '[테스트] 정렬 순서에 따라 데이터 호출하기',
		duration: 600,
		filename: '[테스트 파일명] 정렬 순서에 따라 데이터 호출하기',
		courseId: 3,
		sectionId: 6,
		createdAt: new Date(2022, 1, 1),
	},
	{
		id: 15,
		title: '[테스트] 데이터를 가져오는 동안 로딩 화면 보여주기',
		duration: 600,
		filename: '[테스트 파일명] 데이터를 가져오는 동안 로딩 화면 보여주기',
		courseId: 3,
		sectionId: 6,
		createdAt: new Date(2022, 1, 1),
	},
	{
		id: 16,
		title: '[테스트] Vue 인스턴스 생성하기',
		duration: 600,
		filename: '[테스트 파일명] Vue 인스턴스 생성하기',
		courseId: 4,
		sectionId: 7,
		createdAt: new Date(2022, 1, 1),
	},
	{
		id: 17,
		title: '[테스트] 여러 개의 뷰 인스턴스 사용하기',
		duration: 600,
		filename: '[테스트 파일명] 여러 개의 뷰 인스턴스 사용하기 ',
		courseId: 4,
		sectionId: 7,
		createdAt: new Date(2022, 1, 1),
	},
	{
		id: 18,
		title: '[테스트] 부모&자식 컴포넌트로 데이터 보내기',
		duration: 600,
		filename: '[테스트 파일명] 부모&자식 컴포넌트로 데이터 보내기',
		courseId: 4,
		sectionId: 8,
		createdAt: new Date(2022, 1, 1),
	},
	{
		id: 19,
		title: '[테스트] 뷰 인스턴스 라이프사이클 ',
		duration: 600,
		filename: '[테스트 파일명] 뷰 인스턴스 라이프사이클 ',
		courseId: 4,
		sectionId: 8,
		createdAt: new Date(2022, 1, 1),
	},
	{
		id: 20,
		title: '[테스트] Vue Getters & Map 핼퍼',
		duration: 600,
		filename: '[테스트 파일명] Vue Getters & Map 햂퍼',
		courseId: 4,
		sectionId: 9,
		createdAt: new Date(2022, 1, 1),
	},
	{
		id: 21,
		title: '[테스트] 도커 이미지 pull',
		duration: 600,
		filename: '[테스트 파일명] 도커 이미지 pull',
		courseId: 5,
		sectionId: 10,
		createdAt: new Date(2022, 1, 1),
	},
	{
		id: 22,
		title: '[테스트] 도커 컨테이너 run',
		duration: 600,
		filename: '[테스트 파일명] 도커 컨테이너 run',
		courseId: 5,
		sectionId: 11,
		createdAt: new Date(2022, 1, 1),
	},
	{
		id: 23,
		title: '[테스트] 도커 네트워크',
		duration: 600,
		filename: '[테스트 파일명] 도커 네트워크',
		courseId: 5,
		sectionId: 12,
		createdAt: new Date(2022, 1, 1),
	},
	{
		id: 24,
		title: '[테스트] 도커 명령어 실행',
		duration: 600,
		filename: '[테스트 파일명] 도커 명령어 실행',
		courseId: 5,
		sectionId: 13,
		createdAt: new Date(2022, 1, 1),
	},
	{
		id: 25,
		title: '[테스트] 호스트와 컨테이너의 파일 시스템 연결',
		duration: 600,
		filename: '[테스트 파일명] 호스트와 컨테이너 파일 시스템 연결',
		courseId: 5,
		sectionId: 14,
		createdAt: new Date(2022, 1, 1),
	},
	{
		id: 26,
		title: '[테스트] 클라우드에 대한 이해',
		duration: 600,
		filename: '[테스트 파일명] 클라우드에 대한 이해',
		courseId: 6,
		sectionId: 15,
		createdAt: new Date(2022, 1, 1),
	},
	{
		id: 27,
		title: '[테스트] 가상 서버 만들기 EC2',
		duration: 600,
		filename: '[테스트 파일명] 가상 서버 만들기 EC2',
		courseId: 6,
		sectionId: 15,
		createdAt: new Date(2022, 1, 1),
	},
	{
		id: 28,
		title: '[테스트] ssh로 EC2 인스턴스 접속하기',
		duration: 600,
		filename: '[테스트 파일명] ssh로 EC2 인스턴스 접속하기',
		courseId: 6,
		sectionId: 15,
		createdAt: new Date(2022, 1, 1),
	},
	{
		id: 29,
		title: '[테스트] 가상 서버의 용량 조절하기 EBS',
		duration: 600,
		filename: '[테스트 파일명] 가상 서버의 용량 조절하기 EBS',
		courseId: 6,
		sectionId: 16,
		createdAt: new Date(2022, 1, 1),
	},
	{
		id: 30,
		title: '[테스트] 자동으로 크기 조절하기 Auto Scaling',
		duration: 600,
		filename: '[테스트 파일명] 자동으로 크기 조절하기 Auto Scaling',
		courseId: 6,
		sectionId: 16,
		createdAt: new Date(2022, 1, 1),
	},
];
