export const Question = [
	{
		id: 1,
		userId: 1,
		courseId: 1,
		lectureId: null,
		contents: 'course 1 질문1 입니다.',
		createdAt: new Date(2022, 7, 1),
	},
	{
		id: 2,
		userId: 1,
		courseId: 1,
		lectureId: null,
		contents: 'course 1 질문2 입니다.',
		createdAt: new Date(2022, 7, 1),
	},
	{
		id: 3,
		userId: 1,
		courseId: 1,
		lectureId: null,
		contents: 'course 1 질문3 입니다.',
		createdAt: new Date(2022, 7, 1),
	},
	{
		id: 4,
		userId: 1,
		courseId: 2,
		lectureId: null,
		contents: 'course 2 질문1 입니다.',
		createdAt: new Date(2022, 7, 1),
	},
	{
		id: 5,
		userId: 1,
		courseId: 2,
		lectureId: null,
		contents: 'course 2 질문2 입니다.',
		createdAt: new Date(2022, 7, 1),
	},
	{
		id: 6,
		userId: 1,
		courseId: 2,
		lectureId: null,
		contents: 'course 2 질문3 입니다.',
		createdAt: new Date(2022, 7, 1),
	},
	{
		id: 7,
		userId: 1,
		courseId: 3,
		lectureId: null,
		contents: 'course 3 질문1 입니다.',
		createdAt: new Date(2022, 7, 1),
	},
	{
		id: 8,
		userId: 1,
		courseId: 3,
		lectureId: null,
		contents: 'course 3 질문2 입니다.',
		createdAt: new Date(2022, 7, 1),
	},
	{
		id: 9,
		userId: 1,
		courseId: 3,
		lectureId: null,
		contents: 'course 3 질문3 입니다.',
		createdAt: new Date(2022, 7, 1),
	},
	{
		id: 10,
		userId: 1,
		courseId: 4,
		lectureId: null,
		contents: 'course 4 질문1 입니다.',
		createdAt: new Date(2022, 7, 1),
	},
	{
		id: 11,
		userId: 1,
		courseId: 4,
		lectureId: null,
		contents: 'course 4 질문2 입니다.',
		createdAt: new Date(2022, 7, 1),
	},
	{
		id: 12,
		userId: 1,
		courseId: 4,
		lectureId: null,
		contents: 'course 4 질문3 입니다.',
		createdAt: new Date(2022, 7, 1),
	},
	{
		id: 13,
		userId: 1,
		courseId: 5,
		lectureId: null,
		contents: 'course 5 질문1 입니다.',
		createdAt: new Date(2022, 7, 1),
	},
	{
		id: 14,
		userId: 1,
		courseId: 5,
		lectureId: null,
		contents: 'course 5 질문2 입니다.',
		createdAt: new Date(2022, 7, 1),
	},
	{
		id: 15,
		userId: 1,
		courseId: 5,
		lectureId: null,
		contents: 'course 5 질문3 입니다.',
		createdAt: new Date(2022, 7, 1),
	},
	{
		id: 16,
		userId: 1,
		courseId: 6,
		lectureId: null,
		contents: 'course 6 질문1 입니다.',
		createdAt: new Date(2022, 7, 1),
	},
	{
		id: 17,
		userId: 1,
		courseId: 6,
		lectureId: null,
		contents: 'course 6 질문2 입니다.',
		createdAt: new Date(2022, 7, 1),
	},
	{
		id: 18,
		userId: 1,
		courseId: 7,
		lectureId: null,
		contents: 'course 7 질문1 입니다.',
		createdAt: new Date(2022, 7, 1),
	},
	{
		id: 19,
		userId: 1,
		courseId: 7,
		lectureId: null,
		contents: 'course 7 질문2 입니다.',
		createdAt: new Date(2022, 7, 1),
	},
	{
		id: 20,
		userId: 1,
		courseId: 8,
		lectureId: null,
		contents: 'course 8 질문1 입니다.',
		createdAt: new Date(2022, 7, 1),
	},
	{
		id: 21,
		userId: 1,
		courseId: 8,
		lectureId: null,
		contents: 'course 8 질문2 입니다.',
		createdAt: new Date(2022, 7, 1),
	},
	{
		id: 22,
		userId: 1,
		courseId: 9,
		lectureId: null,
		contents: 'course 9 질문1 입니다.',
		createdAt: new Date(2022, 7, 1),
	},
	{
		id: 23,
		userId: 1,
		courseId: 9,
		lectureId: null,
		contents: 'course 9 질문2 입니다.',
		createdAt: new Date(2022, 7, 1),
	},
	{
		id: 24,
		userId: 1,
		courseId: 10,
		lectureId: null,
		contents: 'course 10 질문1 입니다.',
		createdAt: new Date(2022, 7, 1),
	},
	{
		id: 25,
		userId: 1,
		courseId: 10,
		lectureId: null,
		contents: 'course 10 질문2 입니다.',
		createdAt: new Date(2022, 7, 1),
	},
	{
		id: 26,
		userId: 1,
		courseId: 11,
		lectureId: null,
		contents: 'course 11 질문1 입니다.',
		createdAt: new Date(2022, 7, 1),
	},
	{
		id: 27,
		userId: 1,
		courseId: 11,
		lectureId: null,
		contents: 'course 11 질문2 입니다.',
		createdAt: new Date(2022, 7, 1),
	},
	{
		id: 28,
		userId: 1,
		courseId: 12,
		lectureId: null,
		contents: 'course 12 질문1 입니다.',
		createdAt: new Date(2022, 7, 1),
	},
	{
		id: 29,
		userId: 1,
		courseId: 12,
		lectureId: null,
		contents: 'course 12 질문2 입니다.',
		createdAt: new Date(2022, 7, 1),
	},
	{
		id: 30,
		userId: 1,
		courseId: 13,
		lectureId: null,
		contents: 'course 13 질문1 입니다.',
		createdAt: new Date(2022, 7, 1),
	},
];
