name: CI

on:
    push:
        branches: ['main']

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Run scripts in server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_KEY }}
                  script: |
                      cd mvp-backend-nestjs/
                      rm -rf ./dist
                      git pull origin main
                      npm install
                      pm2 restart 0
